server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka, http://localhost:8766/eureka
spring:
  application:
    name: ShippingService
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)